const data = [
    ["GPU ↑↓", "Price ($/h) ↑↓", "VRAM ↑↓", "Provider ↑↓", "Link ↑↓"],
    ["H100", "3.24", "80 GB", "Ori.co", "https://www.ori.co"],
    ["A100", "2.74", "80 GB", "Ori.co", "https://www.ori.co"],
    ["L40S", "1.96", "48 GB", "Ori.co", "https://www.ori.co"],
    ["V100/S", "0.83", "16 GB", "Ori.co", "https://www.ori.co"],
    ["A16", "0.54", "16 GB", "Ori.co", "https://www.ori.co"],
    ["NVIDIA HGX H100", "4.76", "80 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["H100 PCIe", "4.25", "80 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["A100 80GB NVLINK", "2.21", "80 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["A100 80GB PCIe", "2.21", "80 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["A100 40GB NVLINK", "2.06", "40 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["A100 40GB PCIe", "2.06", "40 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["A40", "1.28", "48 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["RTX A6000", "1.28", "48 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["RTX A5000", "0.77", "24 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["RTX A4000", "0.61", "16 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["Quadro RTX 5000", "0.57", "16 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["Quadro RTX 4000", "0.24", "8 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["Tesla V100 NVLINK", "0.80", "16 GB", "CoreWeave", "https://www.coreweave.com/gpu-cloud-pricing"],
    ["Nvidia A100 (40GB) GPU", "4.14", "40 GB", "Replicate", "https://replicate.com/pricing"],
    ["2x Nvidia A100 (40GB)", "8.28", "80 GB", "Replicate", "https://replicate.com/pricing"],
    ["4x Nvidia A100 (40GB)", "16.56", "160 GB", "Replicate", "https://replicate.com/pricing"],
    ["Nvidia A100 (80GB) GPU", "5.04", "80 GB", "Replicate", "https://replicate.com/pricing"],
    ["2x Nvidia A100 (80GB)", "10.08", "160 GB", "Replicate", "https://replicate.com/pricing"],
    ["4x Nvidia A100 (80GB)", "20.16", "320 GB", "Replicate", "https://replicate.com/pricing"],
    ["8x Nvidia A100 (80GB)", "40.32", "640 GB", "Replicate", "https://replicate.com/pricing"],
    ["Nvidia A40 (Large) GPU", "2.61", "48 GB", "Replicate", "https://replicate.com/pricing"],
    ["2x Nvidia A40 (Large)", "5.22", "96 GB", "Replicate", "https://replicate.com/pricing"],
    ["4x Nvidia A40 (Large)", "10.44", "192 GB", "Replicate", "https://replicate.com/pricing"],
    ["8x Nvidia A40 (Large)", "20.88", "384 GB", "Replicate", "https://replicate.com/pricing"],
    ["Nvidia A40 GPU", "2.07", "48 GB", "Replicate", "https://replicate.com/pricing"],
    ["Nvidia T4 GPU", "0.81", "16 GB", "Replicate", "https://replicate.com/pricing"],
    ["NVIDIA H100 PCIe", "2.49", "80 GB", "Lambda Labs", "https://lambdalabs.com/service/gpu-cloud"],
    ["NVIDIA H100 SXM", "27.92", "80 GB", "Lambda Labs", "https://lambdalabs.com/service/gpu-cloud"],
    ["NVIDIA A100 SXM", "1.29", "40 GB", "Lambda Labs", "https://lambdalabs.com/service/gpu-cloud"],
    ["NVIDIA A100 PCIe", "1.29", "40 GB", "Lambda Labs", "https://lambdalabs.com/service/gpu-cloud"],
    ["NVIDIA A10", "0.75", "24 GB", "Lambda Labs", "https://lambdalabs.com/service/gpu-cloud"],
    ["NVIDIA A6000", "0.80", "48 GB", "Lambda Labs", "https://lambdalabs.com/service/gpu-cloud"],
    ["NVIDIA Tesla V100", "4.40", "16 GB", "Lambda Labs", "https://lambdalabs.com/service/gpu-cloud"],
    ["NVIDIA Quadro RTX 6000", "0.50", "24 GB", "Lambda Labs", "https://lambdalabs.com/service/gpu-cloud"]
];
